spring.application.name=recipemanagement
spring.datasource.username=springstudent
spring.datasource.password=springstudent
spring.datasource.url=jdbc:mysql://localhost:3306/recipe-management-system
spring.jpa.hibernate.ddl-auto=update
jwt.secret=mysecretkeymysecretkeymysecretkeymysecretkey

cloudinary.cloud_name=dmzwzkz4h
cloudinary.api_key=178985118786784
cloudinary.api_secret=5iNJHog9C48a9nlfOtKJhQX-VIo